
["The World of Lilith"]
cover = "https://xfs-n07.xfsbb.com/thumb/W600/ampi/aee/aee6c1123cc43eafec243022bc696b1c596c8ed9_430_570_53161.jpg"
author = "Lala二世"
artist = "Lala二世"
description = "Lilith, a 500-year-old vampire, is determined to leave her harem of pretty boys ! Will she be left alone in the human world ? Or will she starve herself ?"
chapter_ids = [1_683_072, 1_683_067, 1_683_060, 1_683_057, 1_683_045]

["Love Rides on Pheromone Allergy"]
cover = "https://xfs-n03.xfsbb.com/thumb/W600/ampi/d3e/d3e17482c3b12e9c7c4f7896158b137018efbb77_488_628_115301.jpeg"
author = "Chungye"
artist = "Chungye"
description = """
*Omegaverse + Guiding*

"Who in their right mind would engage in such a thing between friends?"
Cha Jae-Heon, a hot-blooded alpha who hides his feelings by trying to consider a childhood friend just a friend with the principle of "There shouldn't be any emotions involved!"
One day, while he was satisfied with his friendship with Ki Je-Yeon, a dominant omega and a guide, who is allergic to pheromones, a sudden turn of events leads to an unexpected rut guidance sex!
Will Jae-Heon overcome the barriers of pheromone allergy reactions and find true love?"""
chapter_ids = [
    2_850_913,
    2_842_832,
    2_838_268,
    2_816_570,
    2_805_684,
    2_795_626,
    2_786_931,
    2_774_080,
    2_762_741,
    2_731_149,
]
